// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import PdfDownloadController from "./pdf_download_controller"
application.register("pdf-download", PdfDownloadController)

import PdfTrackingController from "./pdf_tracking_controller"
application.register("pdf-tracking", PdfTrackingController)

import ResponsibilityController from "./responsibility_controller"
application.register("responsibility", ResponsibilityController)
