name: CI (Security & Style)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  security_scan:
    name: Security Scan (Brakeman)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false # We'll handle the install ourselves to update gems first

      - name: Update RubyGems and Install
        run: |
          gem update --system 3.3.22
          bundle install

      - run: bundle exec brakeman --no-pager

  style_lint:
    name: Style Lint (RuboCop)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false

      - name: Update RubyGems and Install
        run: |
          gem update --system 3.3.22
          bundle install

      - run: bundle exec rubocop -f github
