name: CI (Security & Style)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  security_scan:
    name: Security Scan (Brakeman)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          # ADD THIS LINE BELOW
          update-rubygems: true
      - run: bundle exec brakeman --no-pager

  style_lint:
    name: Style Lint (RuboCop)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          # ADD THIS LINE BELOW
          update-rubygems: true
      - run: bundle exec rubocop -f github
